### ISSUE TITLE
Not working on Sketch Version 66.1 (97080)?

### ISSUE THREAD

**Issue by quoindesign** [alanfraneo/sketch-neo-preview#1]
Hi, 

I LOVE this plugin! 

I updated Sketch recently and it's not working now. I updated plugin to v1.4. It fails without any error displayed. My artboards are marked for export. 

Will this be updated soon? 

Thanks!
Josh

**Comment by alanfraneo** [comment]
Hi Josh, I didn't know this was used by others :) Great to hear from you. I will fix it ASAP.

**Comment by alanfraneo** [comment]
Caused by removal of old v1 API in v66. [Read more](https://developer.sketch.com/plugins/updates/new-in-sketch-66)

Removed all references to V1 API in the plugin and made a new version release. [Changeset](https://github.com/alanfraneo/sketch-neo-preview/commit/f06e8bb296edfbc26cf00c5c328e76f2d93d8c50)
